/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailStudioRouteImport } from './routes/email-studio'
import { Route as MeetingIntelligenceRouteImport } from './routes/meeting-intelligence'
import { Route as ResearchHubRouteImport } from './routes/research-hub'
import { Route as WorkPlannerRouteImport } from './routes/work-planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailStudioRoute = EmailStudioRouteImport.update({
  id: '/email-studio',
  path: '/email-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIntelligenceRoute = MeetingIntelligenceRouteImport.update({
  id: '/meeting-intelligence',
  path: '/meeting-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchHubRoute = ResearchHubRouteImport.update({
  id: '/research-hub',
  path: '/research-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPlannerRoute = WorkPlannerRouteImport.update({
  id: '/work-planner',
  path: '/work-planner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-studio': typeof EmailStudioRoute
  '/meeting-intelligence': typeof MeetingIntelligenceRoute
  '/research-hub': typeof ResearchHubRoute
  '/work-planner': typeof WorkPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-studio': typeof EmailStudioRoute
  '/meeting-intelligence': typeof MeetingIntelligenceRoute
  '/research-hub': typeof ResearchHubRoute
  '/work-planner': typeof WorkPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-studio': typeof EmailStudioRoute
  '/meeting-intelligence': typeof MeetingIntelligenceRoute
  '/research-hub': typeof ResearchHubRoute
  '/work-planner': typeof WorkPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-studio'
    | '/meeting-intelligence'
    | '/research-hub'
    | '/work-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-studio'
    | '/meeting-intelligence'
    | '/research-hub'
    | '/work-planner'
  id:
    | '__root__'
    | '/'
    | '/email-studio'
    | '/meeting-intelligence'
    | '/research-hub'
    | '/work-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailStudioRoute: typeof EmailStudioRoute
  MeetingIntelligenceRoute: typeof MeetingIntelligenceRoute
  ResearchHubRoute: typeof ResearchHubRoute
  WorkPlannerRoute: typeof WorkPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-studio': {
      id: '/email-studio'
      path: '/email-studio'
      fullPath: '/email-studio'
      preLoaderRoute: typeof EmailStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-intelligence': {
      id: '/meeting-intelligence'
      path: '/meeting-intelligence'
      fullPath: '/meeting-intelligence'
      preLoaderRoute: typeof MeetingIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-hub': {
      id: '/research-hub'
      path: '/research-hub'
      fullPath: '/research-hub'
      preLoaderRoute: typeof ResearchHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-planner': {
      id: '/work-planner'
      path: '/work-planner'
      fullPath: '/work-planner'
      preLoaderRoute: typeof WorkPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailStudioRoute: EmailStudioRoute,
  MeetingIntelligenceRoute: MeetingIntelligenceRoute,
  ResearchHubRoute: ResearchHubRoute,
  WorkPlannerRoute: WorkPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
